### ISSUE TITLE
can not render the template

### ISSUE THREAD

**Issue by kasparslie** [divanov11/StudyBud#16]
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 4.0.1
Python Version: 3.10.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'base.apps.BaseConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.filesystem.Loader: C:\Users\kaspa\Documents\myDjango\studybud\templates\home.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\kaspa\Documents\myDjango\env\lib\site-packages\django\contrib\admin\templates\home.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\kaspa\Documents\myDjango\env\lib\site-packages\django\contrib\auth\templates\home.html (Source does not exist)

Traceback (most recent call last):
  File "C:\Users\kaspa\Documents\myDjango\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\kaspa\Documents\myDjango\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kaspa\Documents\myDjango\studybud\base\views.py", line 6, in home
    return render(request, 'home.html')
  File "C:\Users\kaspa\Documents\myDjango\env\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\kaspa\Documents\myDjango\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\kaspa\Documents\myDjango\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)

Exception Type: TemplateDoesNotExist at /
Exception Value: home.htm
![studybud_urls py](https://user-images.githubusercontent.com/70344729/151708750-78e39aa2-14f4-49a8-9f5a-90ab696e9b69.jpg)
![base_urls py](https://user-images.githubusercontent.com/70344729/151708751-c3322dc3-d2d7-4b84-937f-8c0d5e082bad.jpg)
![base_views py](https://user-images.githubusercontent.com/70344729/151708752-648b164a-756e-4b2c-b890-1fb14a3dfa06.jpg)
![studybud_settings py](https://user-images.githubusercontent.com/70344729/151708754-24e4cd44-3fb3-4cb9-bb8b-648f3fe429e2.jpg)
l

**Comment by kasparslie** [comment]
I found solution folder containing templates werent in base directory, it was one level lower
